<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AutoMove3" Id="{d8ff9495-5edb-4363-8a3f-b0e10d5c02bf}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AutoMove3
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AutoMove3">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>